---
zscan_catalog:
    filenm: "/global/u1/m/mkwiecie/desc/redmapper/dc2_dr6_run_redmapper_v0.8.1_zscan_catalog.fit"
    cluster_id: "mem_match_id"
    richness_steps: "lambda_steps"
    
truth_catalog: 
    filenm: "dc2_redmapper_run2.2i_dr6_wfd_v0.8.1"
    cluster_id: "cluster_id"
    redshift: "redshift"
    richness: "richness"
...